services:
  web:
    build: .
    container_name: odoo17
    restart: always
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
    ports:
      - "8074:8069"
      - "8075:8072"
  db:
    image: postgres:16
    container_name: odoo17_db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  redis:
    image: redis:latest
    container_name: odoo17_redis
    restart: always
    volumes:
      - odoo-redis:/data

volumes:
  odoo-web-data:
  odoo-db-data:
  odoo-redis: